# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under sunny_mlops/resources/*
# and sunny_mlops/databricks.yml with staging deployment target configs,
# when PRs are merged into the default branch
name: Bundle Deployment for sunny_mlops Staging

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./sunny_mlops

env:
  ARM_TENANT_ID: ${{ secrets.STAGING_AZURE_SP_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.STAGING_AZURE_SP_APPLICATION_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.STAGING_AZURE_SP_CLIENT_SECRET }}
  

jobs:
  staging:
    concurrency: sunny_mlops-staging-bundle-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@v0.221.0
      - name: Validate Bundle For Staging
        id: validate
        run: |
          databricks bundle validate -t staging_sunny
      - name: Deploy Bundle to Staging
        id: deploy
        run: |
          databricks bundle deploy -t staging_sunny
